times = ('Palmeiras','Flamengo','Cruzeiro','Internacional','Fluminense','Corinthians','Athletico-PR','Atlético','Fortaleza',"São Paulo",'América','Botafogo','Santos','Goiás','Red Bull Bragantino','Coritiba','Cuiabá','Grêmio','Vasco','Bahia' )
print('='*50)
print(f'Lista de times do Brasileirão: {times}')
print('='*50)
print(f'Os cinco primeiros são: {times[:5]}')
print('='*50)
print(f'Os quatro últimos são: {times[-4:]}')
print('='*50)
print(f'Times em ordem alfabética: {sorted(times)}')
print('='*50)
print(f'O time Palmeiras está na {times.index("Palmeiras")+1}ª posição')
print('='*50)
